---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-d840b523
  labels:
    app: password-generator-d840b523
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: password-generator-d840b523
  template:
    metadata:
      labels:
        app: password-generator-d840b523
    spec:
      serviceAccountName: ingress-manager
      containers:
        - name: password-generator-d840b523
          image: docker.io/phengbunath/password-generator-d840b523:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
